import { z } from 'zod';
import { PluginRegistryV2 } from './plugins/index.js';
import { ActionRunner } from './ActionRunner.js';
import { PuppeteerHelper } from './utils/puppeteer/PuppeteerHelper.js';
import { PromptPreprocessorRegistry } from './preprocessors/PromptPreprocessorRegistry.js';
import { GlobalContext, ServiceCapabilities } from './types.js';
import { LlmClientFactory } from './core/LlmClientFactory.js';
import { StepResolver } from './core/StepResolver.js';
import { MessageBuilder } from './core/MessageBuilder.js';
import { ContentResolver } from './core/io/ContentResolver.js';
export declare const configSchema: z.ZodObject<{
    AI_API_KEY: z.ZodString;
    AI_API_URL: z.ZodDefault<z.ZodString>;
    MODEL: z.ZodOptional<z.ZodString>;
    GPT_MAX_CONVERSATION_CHARS: z.ZodOptional<z.ZodNumber>;
    CACHE_ENABLED: z.ZodDefault<z.ZodBoolean>;
    SQLITE_PATH: z.ZodDefault<z.ZodString>;
    SERPER_API_KEY: z.ZodOptional<z.ZodString>;
    TASK_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    GPT_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    SERPER_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    PUPPETEER_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    PUPPETEER_MAX_PAGES_BEFORE_RESTART: z.ZodDefault<z.ZodNumber>;
    PUPPETEER_RESTART_TIMEOUT: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    AI_API_KEY: string;
    AI_API_URL: string;
    CACHE_ENABLED: boolean;
    SQLITE_PATH: string;
    TASK_CONCURRENCY: number;
    GPT_CONCURRENCY: number;
    SERPER_CONCURRENCY: number;
    PUPPETEER_CONCURRENCY: number;
    PUPPETEER_MAX_PAGES_BEFORE_RESTART: number;
    PUPPETEER_RESTART_TIMEOUT: number;
    MODEL?: string | undefined;
    GPT_MAX_CONVERSATION_CHARS?: number | undefined;
    SERPER_API_KEY?: string | undefined;
}, {
    AI_API_KEY: string;
    AI_API_URL?: string | undefined;
    MODEL?: string | undefined;
    GPT_MAX_CONVERSATION_CHARS?: number | undefined;
    CACHE_ENABLED?: boolean | undefined;
    SQLITE_PATH?: string | undefined;
    SERPER_API_KEY?: string | undefined;
    TASK_CONCURRENCY?: number | undefined;
    GPT_CONCURRENCY?: number | undefined;
    SERPER_CONCURRENCY?: number | undefined;
    PUPPETEER_CONCURRENCY?: number | undefined;
    PUPPETEER_MAX_PAGES_BEFORE_RESTART?: number | undefined;
    PUPPETEER_RESTART_TIMEOUT?: number | undefined;
}>;
export type ConfigOverrides = {
    concurrency?: number;
    contentResolver?: ContentResolver;
};
export declare const createDefaultRegistry: (capabilities: ServiceCapabilities) => PluginRegistryV2;
export declare const createPreprocessorRegistry: () => PromptPreprocessorRegistry;
export declare const initConfig: (overrides?: ConfigOverrides) => Promise<{
    config: {
        AI_API_KEY: string;
        AI_API_URL: string;
        CACHE_ENABLED: boolean;
        SQLITE_PATH: string;
        TASK_CONCURRENCY: number;
        GPT_CONCURRENCY: number;
        SERPER_CONCURRENCY: number;
        PUPPETEER_CONCURRENCY: number;
        PUPPETEER_MAX_PAGES_BEFORE_RESTART: number;
        PUPPETEER_RESTART_TIMEOUT: number;
        MODEL?: string | undefined;
        GPT_MAX_CONVERSATION_CHARS?: number | undefined;
        SERPER_API_KEY?: string | undefined;
    };
    globalContext: GlobalContext;
    pluginRegistry: PluginRegistryV2;
    preprocessorRegistry: PromptPreprocessorRegistry;
    actionRunner: ActionRunner;
    puppeteerHelper: PuppeteerHelper;
    capabilities: ServiceCapabilities;
    llmFactory: LlmClientFactory;
    stepResolver: StepResolver;
    messageBuilder: MessageBuilder;
}>;
export type TheConfig = Awaited<ReturnType<typeof initConfig>>;
export declare const getConfig: (overrides?: ConfigOverrides) => Promise<{
    config: {
        AI_API_KEY: string;
        AI_API_URL: string;
        CACHE_ENABLED: boolean;
        SQLITE_PATH: string;
        TASK_CONCURRENCY: number;
        GPT_CONCURRENCY: number;
        SERPER_CONCURRENCY: number;
        PUPPETEER_CONCURRENCY: number;
        PUPPETEER_MAX_PAGES_BEFORE_RESTART: number;
        PUPPETEER_RESTART_TIMEOUT: number;
        MODEL?: string | undefined;
        GPT_MAX_CONVERSATION_CHARS?: number | undefined;
        SERPER_API_KEY?: string | undefined;
    };
    globalContext: GlobalContext;
    pluginRegistry: PluginRegistryV2;
    preprocessorRegistry: PromptPreprocessorRegistry;
    actionRunner: ActionRunner;
    puppeteerHelper: PuppeteerHelper;
    capabilities: ServiceCapabilities;
    llmFactory: LlmClientFactory;
    stepResolver: StepResolver;
    messageBuilder: MessageBuilder;
}>;
//# sourceMappingURL=getConfig.d.ts.map