#!/bin/bash
PATHS="packages/llm-fns/src"
if [ -d "packages/llm-fns/tests" ]; then
    PATHS="$PATHS packages/llm-fns/tests"
fi

aider $(find $PATHS -type f \( -name "*.ts" -o -name "*.js" \) ! -name "*.d.ts" -print) "$@"
