import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const outputFile = path.join(rootDir, 'src', 'generated', 'ConfigDocumentation.ts');
const examplesDir = path.join(rootDir, '../../apps/batchprompt-cli/examples');

// Ensure output directory exists
const outputDir = path.dirname(outputFile);
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

let content = '';

// Helper to append file
function appendFile(filePath: string) {
    if (!fs.existsSync(filePath)) return;
    const relativePath = path.relative(rootDir, filePath);
    const fileContent = fs.readFileSync(filePath, 'utf-8');
    content += `${relativePath}\n\`\`\`\n${fileContent}\n\`\`\`\n\n`;
}

console.log('Generating Config Documentation...');

// 1. README
console.log('  - Reading README.md...');
appendFile(path.join(rootDir, 'README.md'));

// 2. Examples (Only README.md and config*.json)
console.log('  - Reading Examples...');
const exampleFiles = findFiles(examplesDir).filter(file => {
    const basename = path.basename(file);
    return basename === 'README.md' || (basename.startsWith('config') && basename.endsWith('.json'));
});

for (const file of exampleFiles) {
    appendFile(file);
}

// Escape for Template Literal
// 1. Backslashes must be escaped first (e.g. \n -> \\n)
// 2. Backticks must be escaped (e.g. ` -> \`)
// 3. ${ must be escaped (e.g. ${ -> \${)
const escapedContent = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\${/g, '\\${');

const tsContent = `/**
 * Auto-generated documentation for configuration generation.
 * Do not edit manually.
 * Generated by scripts/create-docs-ts.ts
 */

export const CONFIG_DOCUMENTATION = \`${escapedContent}\`;
`;

fs.writeFileSync(outputFile, tsContent);
console.log(`✔ Generated ${outputFile} (${(tsContent.length / 1024).toFixed(2)} KB)`);

function findFiles(dir: string): string[] {
    let results: string[] = [];
    if (!fs.existsSync(dir)) return results;
    
    const list = fs.readdirSync(dir);
    for (const file of list) {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);
        if (stat && stat.isDirectory()) {
            if (!file.startsWith('.')) {
                results = results.concat(findFiles(filePath));
            }
        } else {
            if (!file.startsWith('.')) {
                results.push(filePath);
            }
        }
    }
    return results.sort();
}
