import { describe, it, expect } from 'vitest';
import { setupTestEnvironment } from '../utils/testUtils.js';
import { WebSearch } from '../../src/plugins/web-search/WebSearch.js';

// Mock WebSearch
class MockWebSearch extends WebSearch {
    constructor() {
        super('mock-key', null as any, null as any);
    }
    async search(query: string) {
        // Return mixed results
        return [
            { title: 'Competitor A', link: 'https://comp-a.com', snippet: 'Snippet A', type: 'seo' as const },
            { title: 'Butlerapp Home', link: 'https://butlerapp.de', snippet: 'Butlerapp Homepage', type: 'seo' as const },
            { title: 'Competitor B', link: 'https://comp-b.com', snippet: 'Snippet B', type: 'seo' as const },
            { title: 'Butlerapp Pricing', link: 'https://butlerapp.de/pricing', snippet: 'Butlerapp Pricing', type: 'seo' as const }
        ];
    }
}

describe('E2E SEO Rank', () => {
    it('should filter search results using selectPrompt and explode them', async () => {
        // Mock Responses for the LLM Selector
        const mockResponses = [
            // Response for "Select up to 10 links..."
            JSON.stringify({
                selected_indices: [1, 3],
                reasoning: "Selected links pointing to butlerapp.de"
            }),
            // Response for the main model step (if it runs, but we expect pass-through now)
            "Analysis complete."
        ];

        const mockWebSearch = new MockWebSearch();
        const { executor } = setupTestEnvironment({
            mockResponses,
            webSearch: mockWebSearch
        });

        const config = {
            globals: { model: "gpt-mock" },
            steps: [
                {
                    // Step Output Config (Moved from plugin to step to work with StepRow)
                    output: {
                        mode: "merge",
                        explode: true
                    },
                    plugins: [
                        {
                            type: "web-search",
                            query: "{{keyword}}",
                            maxPages: 1,
                            limit: 30,
                            mode: "none",
                            // Fixed: selectPrompt -> selectModel
                            selectModel: {
                                prompt: "Select links for Butlerapp"
                            }
                            // Removed output from plugin as StepRow uses step output
                        }
                    ]
                }
            ]
        };

        const initialRows = [{ keyword: "kursverwaltung" }];

        const { results } = await executor.runConfig(config, initialRows);

        // We expect 2 results because 2 links were selected and exploded
        expect(results).toHaveLength(2);

        // Since we are in pass-through mode, the result is the object generated by the plugin.
        // The plugin output is namespaced under 'webSearch' (camelCase of 'web-search').
        // Wait, WebSearchPluginV2 returns result.data which is an array of WebSearchResult.
        // StepRow merges this array into the row?
        // If explode is true, it iterates the array.
        // itemData is one WebSearchResult.
        // applyOutput(mode: merge) merges itemData into row.
        // WebSearchResult has { title, link, ... }.
        // So results[0].title should be "Butlerapp Home".
        
        expect(results[0].title).toBe("Butlerapp Home");
        expect(results[0].link).toBe("https://butlerapp.de");
        expect(results[0].keyword).toBe("kursverwaltung");

        expect(results[1].title).toBe("Butlerapp Pricing");
        expect(results[1].link).toBe("https://butlerapp.de/pricing");
        expect(results[1].keyword).toBe("kursverwaltung");
    });
});
