"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fs_1 = require("fs");
var path_1 = require("path");
var url_1 = require("url");
var __filename = (0, url_1.fileURLToPath)(import.meta.url);
var __dirname = path_1.default.dirname(__filename);
var rootDir = path_1.default.resolve(__dirname, '..');
var outputFile = path_1.default.join(rootDir, 'src', 'generated', 'ConfigDocumentation.ts');
var examplesDir = path_1.default.join(rootDir, 'examples');
// Ensure output directory exists
var outputDir = path_1.default.dirname(outputFile);
if (!fs_1.default.existsSync(outputDir)) {
    fs_1.default.mkdirSync(outputDir, { recursive: true });
}
var content = '';
// Helper to append file
function appendFile(filePath) {
    if (!fs_1.default.existsSync(filePath))
        return;
    var relativePath = path_1.default.relative(rootDir, filePath);
    var fileContent = fs_1.default.readFileSync(filePath, 'utf-8');
    content += "".concat(relativePath, "\n```\n").concat(fileContent, "\n```\n\n");
}
console.log('Generating Config Documentation...');
// 1. README
console.log('  - Reading README.md...');
appendFile(path_1.default.join(rootDir, 'README.md'));
// 2. Examples (Only README.md and config*.json)
console.log('  - Reading Examples...');
var exampleFiles = findFiles(examplesDir).filter(function (file) {
    var basename = path_1.default.basename(file);
    return basename === 'README.md' || (basename.startsWith('config') && basename.endsWith('.json'));
});
for (var _i = 0, exampleFiles_1 = exampleFiles; _i < exampleFiles_1.length; _i++) {
    var file = exampleFiles_1[_i];
    appendFile(file);
}
// Escape for Template Literal
// 1. Backslashes must be escaped first (e.g. \n -> \\n)
// 2. Backticks must be escaped (e.g. ` -> \`)
// 3. ${ must be escaped (e.g. ${ -> \${)
var escapedContent = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\${/g, '\\${');
var tsContent = "/**\n * Auto-generated documentation for configuration generation.\n * Do not edit manually.\n * Generated by scripts/create-docs-ts.ts\n */\n\nexport const CONFIG_DOCUMENTATION = `".concat(escapedContent, "`;\n");
fs_1.default.writeFileSync(outputFile, tsContent);
console.log("\u2714 Generated ".concat(outputFile, " (").concat((tsContent.length / 1024).toFixed(2), " KB)"));
function findFiles(dir) {
    var results = [];
    if (!fs_1.default.existsSync(dir))
        return results;
    var list = fs_1.default.readdirSync(dir);
    for (var _i = 0, list_1 = list; _i < list_1.length; _i++) {
        var file = list_1[_i];
        var filePath = path_1.default.join(dir, file);
        var stat = fs_1.default.statSync(filePath);
        if (stat && stat.isDirectory()) {
            if (!file.startsWith('.')) {
                results = results.concat(findFiles(filePath));
            }
        }
        else {
            if (!file.startsWith('.')) {
                results.push(filePath);
            }
        }
    }
    return results.sort();
}
